description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Ubuntu"
      fonts: 
        - 
          asset: "fonts/Ubuntu-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Nunito"
      fonts: 
        - 
          asset: "fonts/Nunito-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Nunito-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true