import 'package:flutter/material.dart';
import 'package:flutterapp/blood_20donationapp/generatedfirstpagewidget/generated/GeneratedFrame3Widget8.dart';

/* Frame first page 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 926.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 428.0,
                    height: 926.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 428.0,
                            height: 926.0,
                            child: GeneratedFrame3Widget8(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
